# tar: (c)reate g(z)ip (v)erbose (f)ile [filename.tar.gz] [contents]...
tar -czvf ./TradeMania.tar.gz ./TradeMania.jar

# zip: (r)ecursive [filename.zip] [contents]...
zip -r ./TradeMania.zip ./TradeMania.jar
