name: Trade_Mania
main: io.github.Andrew_College.TradeMania.TradeMania
version: ${version}

commands:
  mkTrade:
    description: Creates a trade post with (a) specific player(s) (if specified)
    usage:  /<command> [player] [player] etc.
    permission: <plugin name>.basic
    permission-message:  You can't do that chief! Ask an admin or make a private trade. 